name: Check on Invalid PR

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'data.json'
      - 'CONTRIBUTING.md'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: sleep 20
      
