name: Check on Invalid PR

on:
  pull_request:
    branches:
      - main

jobs:
  job_18:
    runs-on: ubuntu-latest
    steps:
      - name: Print job name
        run: echo "job_18"
      - name: Sleep
        run: sleep 20

  job_19:
    runs-on: ubuntu-latest
    steps:
      - name: Print job name
        run: echo "job_19"
      - name: Sleep
        run: sleep 20

  job_20:
    runs-on: ubuntu-latest
    steps:
      - name: Print job name
        run: echo "job_20"
      - name: Sleep
        run: sleep 20
      
